# -*- coding: utf-8 -*-
"""Extract and Prepare Text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ePuLnDMvxg1cZhAUWgXSljXKwyvs4MY
"""

import fitz  # PyMuPDF
import re

def extract_text_from_pdf(pdf_path, title_page_number=0, contents_page_number=1):
    doc = fitz.open(pdf_path)
    text = ""

    for page_num in range(doc.page_count):
        if page_num == title_page_number or page_num == contents_page_number:
            continue

        page = doc.load_page(page_num)
        page_text = page.get_text()

        # Remove headers and footers, assuming they contain page numbers or section numbers
        lines = page_text.split('\n')
        filtered_lines = []

        for line in lines:
            # Remove lines that are likely page numbers or section numbers
            if re.match(r'^\d+$', line.strip()) or re.match(r'^[IVXLCDM]+\.$', line.strip(), re.IGNORECASE):
                continue
            filtered_lines.append(line)

        filtered_text = '\n'.join(filtered_lines)
        text += filtered_text + "\n"

    return text

def write_text_to_file(text, output_path):
    with open(output_path, 'w') as file:
        file.write(text)

def main(input_pdf, output_text):
    text = extract_text_from_pdf(input_pdf)
    write_text_to_file(text, output_text)
    print(f"Extracted text has been written to {output_text}")

if __name__ == "__main__":
    input_pdf = "your_file.pdf"
    output_text = "extracted_text.txt"
    main(input_pdf, output_text)