# -*- coding: utf-8 -*-
"""Virtual Raphael Ambiguity Conditional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yx4z-RmgdchbLpEJ8suS4dGbWdnXpbOB
"""

import spacy

# List of conditional and disjunctive conjunctions
conditional_conjunctions = ["if", "when", "unless", "as long as", "provided that", "in case"]
disjunctive_conjunctions = ["or", "either"]

def detect_conditional_conjunctions(doc):
    for token in doc:
        if token.text.lower() in conditional_conjunctions:
            return True
    return False

def detect_disjunctive_conjunctions(doc):
    for token in doc:
        if token.text.lower() in disjunctive_conjunctions:
            return True
    return False

def detect_nested_conditions(doc):
    condition_count = 0
    for token in doc:
        if token.text.lower() in conditional_conjunctions:
            condition_count += 1
        if condition_count > 1:
            return True
    return False

def analyze_sentences(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    ambiguous_sentences = []

    for sent in doc.sents:
        has_conditional_conjunction = detect_conditional_conjunctions(sent)
        has_disjunctive_conjunction = detect_disjunctive_conjunctions(sent)
        has_nested_conditions = detect_nested_conditions(sent)

        if has_conditional_conjunction and (has_disjunctive_conjunction or has_nested_conditions):
            ambiguous_sentences.append(sent.text)

    return ambiguous_sentences

def read_input_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

def write_output_file(sentences, output_path):
    with open(output_path, 'w') as file:
        for sentence in sentences:
            file.write(sentence + "\n")

def main(input_file, output_file):
    text = read_input_file(input_file)
    ambiguous_sentences = analyze_sentences(text)
    write_output_file(ambiguous_sentences, output_file)
    print(f"Potentially ambiguous sentences have been written to {output_file}")

if __name__ == "__main__":
    input_file = "your_file.txt"
    output_file = "Potentially Ambiguous Sentences.txt"
    main(input_file, output_file)