# -*- coding: utf-8 -*-
"""Virtual Raphael Ambiguity Temporal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RyDVrCvs-ZaNlPsTcomZgcbAFSz-tdY
"""

import spacy

# List of vague temporal words and expressions
vague_temporal_words = [
    "frequently", "periodically", "every so often", "sometimes", "occasionally",
    "often", "regularly", "from time to time", "at times", "once in a while",
    "rarely", "seldom", "usually", "generally", "normally", "typically", "extended time"
]

# List of temporal conjunctions and adverbs
temporal_conjunctions = [
    "before", "after", "during", "simultaneously", "while", "when", "until",
    "once", "since", "as soon as", "whenever"
]

def detect_vague_temporal_words(doc):
    for token in doc:
        if token.text.lower() in vague_temporal_words:
            return True
    return False

def detect_temporal_conjunction_ambiguities(doc):
    for token in doc:
        if token.text.lower() in temporal_conjunctions:
            # Check the dependency relations to determine potential ambiguity
            head = token.head
            if head and head.pos_ in ["VERB", "AUX"]:
                for child in head.children:
                    if child.dep_ in ["advcl", "prep", "mark"] and child != token:
                        return True
    return False

def analyze_sentences(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    ambiguous_sentences = []

    for sent in doc.sents:
        has_vague_temporal_word = detect_vague_temporal_words(sent)
        has_temporal_conjunction_ambiguity = detect_temporal_conjunction_ambiguities(sent)

        if has_vague_temporal_word or has_temporal_conjunction_ambiguity:
            ambiguous_sentences.append(sent.text)

    return ambiguous_sentences

def read_input_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

def write_output_file(sentences, output_path):
    with open(output_path, 'w') as file:
        for sentence in sentences:
            file.write(sentence + "\n")

def main(input_file, output_file):
    text = read_input_file(input_file)
    ambiguous_sentences = analyze_sentences(text)
    write_output_file(ambiguous_sentences, output_file)
    print(f"Potentially ambiguous sentences have been written to {output_file}")

if __name__ == "__main__":
    input_file = "your_file.txt"
    output_file = "Potentially Ambiguous Sentences.txt"
    main(input_file, output_file)