# -*- coding: utf-8 -*-
"""Virtual Raphael Ambiguity Quantity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwgsXp8jZwtduerm3BejXlc4re5VxN_R
"""

import spacy

# List of ambiguous quantity-related words and expressions
ambiguous_quantity_words = [
    "some", "many", "a handful", "enough", "several", "few", "numerous",
    "various", "a lot", "plenty", "a bit", "a little", "a couple", "a number of",
    "a portion", "an amount", "more or less", "roughly", "around", "approximately"
]

def detect_ambiguous_quantity_words(doc):
    for token in doc:
        if token.text.lower() in ambiguous_quantity_words:
            return True
    return False

def analyze_sentences(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    ambiguous_sentences = []

    for sent in doc.sents:
        has_ambiguous_quantity_word = detect_ambiguous_quantity_words(sent)

        if has_ambiguous_quantity_word:
            ambiguous_sentences.append(sent.text)

    return ambiguous_sentences

def read_input_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

def write_output_file(sentences, output_path):
    with open(output_path, 'w') as file:
        for sentence in sentences:
            file.write(sentence + "\n")

def main(input_file, output_file):
    text = read_input_file(input_file)
    ambiguous_sentences = analyze_sentences(text)
    write_output_file(ambiguous_sentences, output_file)
    print(f"Potentially ambiguous sentences have been written to {output_file}")

if __name__ == "__main__":
    input_file = "your_file.txt"
    output_file = "Potentially Ambiguous Sentences.txt"
    main(input_file, output_file)